name: dockerhub

dep:

env:
  hatlonely:
    REGISTRY_SERVER: "{{.registry.hatlonely.server}}"
    REGISTRY_USERNAME: "{{.registry.hatlonely.username}}"
    REGISTRY_PASSWORD: "{{.registry.hatlonely.password}}"
    REGISTRY_NAMESPACE: "{{.registry.hatlonely.namespace}}"

task:
  protobuf:
    const:
      IMAGE_REPOSITORY: "protobuf"
      IMAGE_TAG: "1.0.1"
    step:
      - docker build ${IMAGE_REPOSITORY} --tag=${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
      - docker login --username="${REGISTRY_USERNAME}" --password="${REGISTRY_PASSWORD}" "${REGISTRY_SERVER}"
      - docker tag "${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}" "${REGISTRY_SERVER}/${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
      - docker push "${REGISTRY_SERVER}/${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
