name: dockerhub

dep:

env:
  aliyun:
    REGISTRY_ENDPOINT: "{{ .registry.aliyun.hatlonely.endpoint }}"
    REGISTRY_USERNAME: "{{ .registry.aliyun.hatlonely.username }}"
    REGISTRY_PASSWORD: "{{ .registry.aliyun.hatlonely.password }}"
    REGISTRY_NAMESPACE: "{{ .registry.aliyun.hatlonely.namespace }}"
  docker:
    REGISTRY_ENDPOINT: "{{ .registry.docker.hatlonely.endpoint }}"
    REGISTRY_USERNAME: "{{ .registry.docker.hatlonely.username }}"
    REGISTRY_PASSWORD: "{{ .registry.docker.hatlonely.password }}"
    REGISTRY_NAMESPACE: "{{ .registry.docker.hatlonely.namespace }}"

task:
  protobuf:
    const:
      IMAGE_REPOSITORY: "protobuf"
      IMAGE_TAG: "1.0.1"
    step:
      - docker login --username="${REGISTRY_USERNAME}" --password="${REGISTRY_PASSWORD}" "${REGISTRY_ENDPOINT}"
      - docker build ${IMAGE_REPOSITORY} --tag=${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
      - docker tag "${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}" "${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
      - docker push "${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/${IMAGE_REPOSITORY}:${IMAGE_TAG}"
